from database import get_incident



def get_investigation_report(id):


    incident = get_incident(id)



    if not incident:

        return None




    report = {


        "id": incident[0],


        "time": incident[1],


        "threat": incident[2],


        "severity": incident[3],


        "risk_score": incident[4],


        "mitre": incident[5],


        "status": incident[6],



        # FIXED COLUMN MAPPING

        "response_status":
            incident[7]
            if incident[7]
            else "CONTAINMENT INITIATED",



        "actions":
            incident[8]
            if incident[8] and incident[8] != "[]"
            else
            """
✅ Block malicious sender

✅ Remove phishing emails

✅ Reset affected credentials

✅ Enable MFA

✅ Investigate suspicious domain

✅ Escalate incident to SOC analyst
""",



        "response_time":
            incident[9]
            if incident[9]
            else "Not recorded",



        "analyst":
            incident[10]
            if incident[10]
            else "None",



        "notes":
            incident[11]
            if incident[11]
            else "No investigation notes",




        "alert_status":
            incident[12]
            if incident[12]
            else "NEW",





        "timeline":
        """
Alert generated by SOC monitoring engine

Threat intelligence analysis completed

Incident classified as HIGH severity

Containment actions initiated

SOC analyst review pending
""",





        "evidence":
        """
Suspicious domain detected:
micr0soft-login.xyz

Threat intelligence:
Suspicious reputation detected

Attack Type:
Phishing attempt

MITRE Technique:
T1566 - Phishing
""",





        "analysis":
        """
The alert indicates a possible phishing campaign.
Suspicious indicators suggest an attempt to steal
credentials or deliver malicious content.
""",





        "steps":
        [

            "Analyze sender reputation",

            "Check suspicious URLs",

            "Review affected users",

            "Verify if credentials were exposed"

        ]



    }



    return report