from flask import (
    Flask,
    render_template,
    request,
    redirect,
    jsonify,
    send_file
)

from database import (
    get_incidents,
    get_incident,
    dashboard_stats,
    update_status,
    assign_analyst,
    add_notes
)

import datetime
import io


app = Flask(__name__)



# =====================================
# DASHBOARD HOME
# =====================================

@app.route("/")
def index():

    incidents = get_incidents()

    dashboard = dashboard_stats()

    alerts = []

    seen = set()


    for incident in incidents:

        threat = incident["threat"]

        severity = str(
            incident["severity"]
        ).upper()


        if severity == "HIGH" and threat not in seen:

            alerts.append({

                "type": threat,

                "severity": severity,

                "score": incident["risk_score"],

                "mitre": incident["mitre"]

            })


            seen.add(threat)



    analytics = {

        "average_risk":
        dashboard["average_risk"]

    }



    return render_template(

        "index.html",

        incidents=incidents,

        alerts=alerts,

        dashboard=dashboard,

        analytics=analytics

    )





# =====================================
# DASHBOARD API
# =====================================

@app.route("/api/dashboard")
def dashboard_api():

    incidents = get_incidents()

    stats = dashboard_stats()


    severity_data = {}

    attack_types = {}



    for incident in incidents:


        severity = incident["severity"]

        severity_data[severity] = (
            severity_data.get(severity,0)+1
        )


        attack = incident["threat"]

        attack_types[attack] = (
            attack_types.get(attack,0)+1
        )



    return jsonify({

        "total": stats["total"],

        "high": stats["high"],

        "open": stats["open"],

        "average_risk":
            stats["average_risk"],

        "severity_data":
            severity_data,

        "attack_types":
            attack_types

    })





# =====================================
# UPDATE STATUS
# =====================================

@app.route(
    "/update_status/<int:id>/<status>"
)
def change_status(id,status):

    update_status(
        id,
        status
    )

    return redirect("/")





# =====================================
# ASSIGN ANALYST
# =====================================

@app.route(
    "/assign/<int:id>",
    methods=["POST"]
)
def analyst(id):

    name = request.form.get(
        "analyst"
    )


    assign_analyst(
        id,
        name
    )


    return redirect("/")





# =====================================
# ADD NOTES
# =====================================

@app.route(
    "/notes/<int:id>",
    methods=["POST"]
)
def save_notes(id):

    notes = request.form.get(
        "notes"
    )


    add_notes(
        id,
        notes
    )


    return redirect("/")





# =====================================
# INVESTIGATION REPORT
# =====================================

@app.route(
    "/investigate/<int:id>"
)
def investigate(id):

    incident = get_incident(id)


    timeline = [

        "Alert generated by SOC monitoring engine",

        "Threat intelligence analysis completed",

        "Incident classified",

        "Containment actions initiated",

        "SOC analyst review pending"

    ]


    evidence = [

        "Suspicious activity detected",

        "Threat intelligence checked",

        "MITRE technique mapped"

    ]


    return render_template(

        "investigation.html",

        incident=incident,

        timeline=timeline,

        evidence=evidence

    )





# =====================================
# DOWNLOAD REPORT
# =====================================

@app.route(
    "/download_report/<int:id>"
)
def download_report(id):

    incident = get_incident(id)


    report = f"""

AI SOC INVESTIGATION REPORT


Incident:
{id}


Threat:
{incident["threat"]}


Severity:
{incident["severity"]}


Risk Score:
{incident["risk_score"]}


MITRE:
{incident["mitre"]}


Status:
{incident["status"]}


Generated:
{datetime.datetime.now()}

"""


    file = io.BytesIO(
        report.encode()
    )


    file.seek(0)


    return send_file(

        file,

        download_name=f"incident_{id}.txt",

        as_attachment=True

    )





# =====================================
# RUN APPLICATION
# =====================================

if __name__ == "__main__":

    app.run(

        host="127.0.0.1",

        port=5000,

        debug=True

    )