"""
Sentinel DNA Orchestration Context

Shared investigation state passed between
orchestration agents during execution.

The context is intentionally lightweight.
It stores investigation state only.

Runtime execution, scheduling, retries,
and lifecycle management remain outside
this object.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class OrchestrationContext:
    """
    Investigation workflow context.

    Shared between:

    Investigation Agent
        |
        v
    IOC Enrichment Agent
        |
        v
    Threat Intelligence Agent
        |
        v
    Risk / Decision Engines
    """

    case_id: str

    alert: dict[str, Any]


    # --------------------------------------------------------------
    # Intelligence collections
    # --------------------------------------------------------------

    iocs: list[dict[str, Any]] = field(
        default_factory=list
    )


    evidence: list[dict[str, Any]] = field(
        default_factory=list
    )


    timeline: list[dict[str, Any]] = field(
        default_factory=list
    )


    findings: list[dict[str, Any]] = field(
        default_factory=list
    )


    # --------------------------------------------------------------
    # Agent collaboration state
    # --------------------------------------------------------------

    shared_data: dict[str, Any] = field(
        default_factory=dict
    )


    # --------------------------------------------------------------
    # Agent execution results
    # --------------------------------------------------------------

    results: dict[str, Any] = field(
        default_factory=dict
    )


    # --------------------------------------------------------------
    # Additional metadata
    # --------------------------------------------------------------

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


    # ==============================================================
    # Result management
    # ==============================================================

    def add_result(
        self,
        agent_name: str,
        result: Any,
    ) -> None:
        """
        Store agent execution result.
        """

        self.results[agent_name] = result


    def get_result(
        self,
        agent_name: str,
        default: Any = None,
    ) -> Any:
        """
        Retrieve agent result.
        """

        return self.results.get(
            agent_name,
            default,
        )


    # ==============================================================
    # Shared intelligence management
    # ==============================================================

    def set_shared(
        self,
        key: str,
        value: Any,
    ) -> None:
        """
        Store intelligence generated by an agent.

        Example:

        IOC Agent:

            context.set_shared(
                "ioc_reputation",
                data
            )
        """

        self.shared_data[key] = value


    def get_shared(
        self,
        key: str,
        default: Any = None,
    ) -> Any:
        """
        Retrieve shared intelligence.
        """

        return self.shared_data.get(
            key,
            default,
        )


    # ==============================================================
    # Collection helpers
    # ==============================================================

    def add_ioc(
        self,
        ioc: dict[str, Any],
    ) -> None:
        """
        Add IOC intelligence.
        """

        self.iocs.append(
            ioc
        )


    def add_evidence(
        self,
        evidence: dict[str, Any],
    ) -> None:
        """
        Add investigation evidence.
        """

        self.evidence.append(
            evidence
        )


    def add_timeline_event(
        self,
        event: dict[str, Any],
    ) -> None:
        """
        Add timeline event.
        """

        self.timeline.append(
            event
        )


    def add_finding(
        self,
        finding: dict[str, Any],
    ) -> None:
        """
        Add investigation finding.
        """

        self.findings.append(
            finding
        )


    # ==============================================================
    # Debug representation
    # ==============================================================

    def summary(self) -> dict[str, Any]:
        """
        Return investigation state summary.
        """

        return {
            "case_id": self.case_id,
            "iocs": len(self.iocs),
            "evidence": len(self.evidence),
            "timeline": len(self.timeline),
            "findings": len(self.findings),
            "results": list(
                self.results.keys()
            ),
            "shared_data": list(
                self.shared_data.keys()
            ),
        }